#include "translations.h"

// Inicialización del idioma actual (por defecto ES)
Language currentLanguage = Language::ES;

// Array de traducciones. Puedes agregar más cadenas según tus necesidades.
const Translation translations[] = {
  // Clave                         ES                            ES(MX)                        CA                            EU                            FR                                 DE                                    EN                                IT
  {"ACTIVIDADES",                 "Actividades",                "Actividades",                "Activitats",                  "Jarduerak",                  "Activites",                       "Aktivitaten",                           "Activities",                        "Attivita"},
  {"ADIVINAR",                    "ADIVINAR",                   "ADIVINAR",                   "ENDEVINAR",                   "ASMATU",                     "DEVINER",                         "RATEN",                                 "GUESS",                             "INDOVINARE"},
  {"AJUSTES_SONIDO",              "SONIDO",                     "SONIDO",                     "SO",                          "SOINU",                      "SON",                             "TON",                                   "SOUND",                             "SUONO"},
  {"AMBIENTES",                   "Ambientes",                  "Ambientes",                  "Ambients",                    "Ambienteak",                 "Ambiances",                       "Ambiente",                              "Ambiences",                         "Ambienti"},
  {"APAGANDO_ELEMENTO",           "Apagando elemento...",       "Apagando elemento...",       "Apagant l'element...",        "Elementua itzaltzen...",     "Extinction de l'element...",      "Element ausschalten...",                "Turning off element...",            "Spegnendo elemento..."},
  {"APAGANDO_ELEMENTOS",          "Apagando elementos...",      "Apagando elementos...",      "Apagant l'elements...",       "Elementuak itzaltzen...",    "Extinction de l'elements...",     "Elements ausschalten...",               "Turning off elements...",           "Spegnendo elementos..."},
  {"APAGANDO_SALA",               "Apagando Sala...",           "Apagando Sala...",           "Apagant la Sala...",          "Gela itzaltzen...",          "Extinction de la Salle...",       "Raum ausschalten...",                   "Turning off Room...",               "Spegnendo la Stanza..."},
  {"APAGAR",                      "Apagar",                     "Apagar",                     "Apagar",                      "Itzal",                      "Eteindre",                        "Ausschalten",                           "Turn Off",                          "Spegnere"},
  {"BASICO",                      "BASICO",                     "BASICO",                     "BASIC",                       "BASIQUE",                    "BASIC",                           "BASIC",                                 "BASIC",                             "BASE"},
  {"BRILLO",                      "Brillo",                     "Brillo",                     "Lluminositat",                "Distira",                    "Luminosite",                      "Helligkeit",                            "Brightness",                        "Luminosita"},
  {"BRILLO_ATENUADO",             "Atenuado",                   "Atenuado",                   "Atenuat",                     "Ahulduta",                   "Attenue",                         "Gedimmt",                               "Dimmed",                            "Attenuato"},
  {"BRILLO_NORMAL",               "Normal",                     "Normal",                     "Normal",                      "Normala",                    "Normal",                          "Normal",                                "Normal",                            "Normale"},
  {"CANCEL",                      "Cancelar",                   "Cancelar",                   "Cancel·lar",                  "Ezeztatu",                   "Annuler",                         "Abbrechen",                             "Cancel",                            "Annulla"},
  {"CARGAR_BATERIA",              "Cargar batería",             "Cargar batería",             "Carrega la bateria",          "Bateria kargatu",            "Charger la batterie",             "Batterie laden",                        "Charge battery",                    "Carica batteria"},
  {"COGNITIVAS",                  "Cognitivas",                 "Cognitivas",                 "Cognitives",                  "Kognitiboak",                "Cognitives",                      "Kognitive",                             "Cognitive",                         "Cognitive"},
  {"COMUNICADOR",                 "Comunicador",                "Comunicador",                "Comunicador",                 "Komunikatzailea",            "Communicateur",                   "Kommunikator",                          "Communicator",                      "Comunicatore"},
  {"CONFIRMAR",                   "Confirmar",                  "Confirmar",                  "Confirmar",                   "Berretsi",                   "Confirmer",                       "Bestätigen",                            "Confirm",                           "Conferma"},
  {"CONFIRM_DELETE",              "Confirmar",                  "Confirmar",                  "Confirmar",                   "Berretsi",                   "Confirmer",                       "Bestätigen",                            "Confirm",                           "Conferma"},
  {"CONTROL_SALA_MENU",           "Control",                    "Control",                    "Control",                     "Kontrola",                   "Contrôle",                        "Steuerung",                             "Control",                           "Controllo"},
  {"CON_NEG",                     "Con respuesta negativa",     "Con respuesta negativa",     "Amb resposta negativa",       "Erantzun negatiboarekin",    "Avec réponse négative",           "Mit negativer Antwort",                 "With negative resp.",               "Con risposta negativa"},
  {"DADO",                        "Dado",                       "Dado",                       "Dau",                         "Dado",                       "Dé",                              "Würfel",                                "Dice",                              "Dado"},
  {"DELETE_ELEMENT",              "Eliminar elemento",          "Eliminar elemento",          "Eliminar element",            "Elementua ezabatu",          "Supprimer élément",               "Element löschen",                       "Delete element",                    "Elimina elemento"},
  {"DELETE_ELEMENT_MENU",         "Eliminar",                   "Eliminar",                   "Eliminar",                    "Elementua",                  "Supprimer",                       "Löschen",                               "Delete",                            "Elimina"},
  {"DESEA_DESHABILITAR_EL_DADO",  "¿Desea deshabilitar el dado?","¿Desea deshabilitar el dado?","Voleu deshabilitar el dau?",  "Dadoa desgaitu nahi duzu?",  "Voulez-vous désactiver le dé ?","Möchten Sie den Würfel deaktivieren?",  "Do you want to disable the dice?",  "Vuoi disabilitare il dado?"},
  {"DESEA_HABILITAR_EL_DADO",     "¿Desea habilitar el dado?",  "¿Desea habilitar el dado?",  "Voleu habilitar el dau?",     "Dadoa gaitu nahi duzu?",     "Voulez-vous activer le dé ?",     "Mochten Sie den Würfel aktivieren?",    "Do you want to enable the dice?",   "Vuoi abilitare il dado?"},
  {"DESHABILITADO",               "Deshabilitado",              "Deshabilitado",              "Deshabilitat",                "Desgaituta",                 "Désactivé",                       "Deaktiviert",                           "Disabled",                          "Disabilitato"},
  {"DESHABILITAR_DADO",           "Deshabilitar Dado",          "Deshabilitar Dado",          "Deshabilitar el Dau",         "Dadoa desgaitu",             "Désactiver le dé",                "Wurfel deaktivieren",                   "Disable Dice",                      "Disabilitare il dado"},
  {"ELEMENTOS_ADICIONALES",       "Elementos adicionales",      "Elementos adicionales",      "Elements addicionals",        "Elementu osagarriak",        "Éléments additionnels",           "Zusätzliche Elemente",                  "Additional Elements",               "Elementi aggiuntivi"},
  {"ENCENDER",                    "Encender",                   "Encender",                   "Encendre",                    "Piztu",                      "Allumer",                         "Einschalten",                           "Turn On",                           "Accendere"},
  {"FICHAS",                      "Fichas",                     "Fichas",                     "Fitxes",                      "Fitxak",                     "Fiches",                          "Fichas",                                "Tokens",                            "Gettoni"},
  {"FORMATEAR",                   "Formatear",                  "Formatear",                  "Formatar",                    "Formatatu",                  "Formater",                        "Formatieren",                           "Format",                            "Formatta"},
  {"HABILITADO",                  "Habilitado",                 "Habilitado",                 "Habilitat",                   "Gaituta",                    "Activé",                          "Aktiviert",                             "Enabled",                           "Abilitato"},
  {"HABILITAR_DADO",              "Habilitar Dado",             "Habilitar Dado",             "Habilitar el Dau",            "Dadoa gaitu",                "Activer le dé",                   "Wurfel aktivieren",                     "Enable Dice",                       "Abilitare il dado"},
  {"HOMBRE",                      "Hombre",                     "Hombre",                     "Home",                        "Gizona",                     "Homme",                           "Mann",                                  "Man",                               "Uomo"},
  {"IDIOMA",                      "Idioma",                     "Idioma",                     "Llengua",                     "Hizkuntza",                  "Langue",                          "Sprache",                               "Language",                          "Lingua"},
  {"MENU_AJUSTAR_BRILLO",         "AJUSTAR BRILLO",             "AJUSTAR BRILLO",             "AJUSTAR LLUM",                "DISTIR BRILOA",              "AJUSTER LUMIERE",                 "HELLIGKEIT EINST.",                     "ADJUST BRIGHTNESS",                 "REGOLA LUMINOSITA"},
  {"MENU_AJUSTES",                "AJUSTES",                    "AJUSTES",                    "CONFIG",                      "EZKARRIA",                   "REGLAGES",                        "EINSTELLUNGEN",                         "SETTINGS",                          "IMPOSTAZIONI"},
  {"MIC_CALIB",                   "Sens. Mic",                  "Sens. Mic",                  "Sens. Micr.",                 "Sens. Mikr.",                "Sens. Mic",                       "Mic-Empf.",                             "Mic Sens.",                         "Sens. Mic"},
  {"MODOS",                       "MODOS",                      "MODOS",                      "MODES",                       "MODUAK",                     "MODES",                           "MODI",                                  "MODES",                             "MODALITA"},
  {"MUJER",                       "Mujer",                      "Mujer",                      "Dona",                        "Emakumea",                   "Femme",                           "Frau",                                  "Woman",                             "Donna"},
  {"NO_DELETE",                   "No",                         "No",                         "No",                          "Ez",                         "Non",                             "Nein",                                  "No",                                "No"},
  {"PAREJAS",                     "PAREJAS",                    "PAREJAS",                    "PARELLES",                    "BIKOIZKAKO",                 "COUPLES",                         "PAARE",                                 "COUPLES",                           "COPPIE"},
  {"RESTORE",                     "¿Restaurar?",                "¿Restaurar?",                "Restaurar?",                  "Berreskuratu?",              "Restaurer ?",                     "Wiederherstellen?",                     "Restore?",                          "Ripristinare?"},
  {"RESTORE_ELEM",                "Restablecer elementos",      "Restablecer elementos",      "Restableix elements",         "Berreskuratu elementuak",    "Restaurer les elements",          "Elemente wiederherstellen",             "Restore elements",                  "Ripristina elementi"},
  {"RESTORE_ROOM",                "¿Restaurar sala?",           "¿Restaurar sala?",           "Restaurar sala?",             "Gela berreskuratu?",         "Restaurer la salle ?",            "Raum wiederherstellen?",                "Restore room?",                     "Ripristinare stanza?"},
  {"ROOM_UPDATED",                "Sala actualizada",           "Sala actualizada",           "Sala actualitzada",           "Gela eguneratua",            "Salle mise a jour",               "Raum aktualisiert",                     "Room updated",                      "Stanza aggiornata"},
  {"SALIR",                       "Salir",                      "Salir",                      "Sortir",                      "Irten",                      "Sortir",                          "Verlassen",                             "Exit",                              "Esci"},
  {"SEARCHING",                   "Buscando",                   "Buscando",                   "Cercant",                     "Bilatzen",                   "Recherche",                       "Suche",                                 "Searching",                         "Ricerca"},
  {"SHOW_ID",                     "Mostrar ID",                 "Mostrar ID",                 "Mostrar ID",                  "ID erakutsi",                "Afficher l'ID",                   "ID anzeigen",                           "Show ID",                           "Mostra ID"},
  {"SIN_NEG",                     "Sin respuesta negativa",     "Sin respuesta negativa",     "Sense resposta negativa",     "Erantzun negatiborik gabe",  "Sans réponse négative",           "Ohne negative Antwort",                 "Without negative resp.",            "Senza risposta negativa"},
  {"SONIDO",                      "Sonido",                     "Sonido",                     "So",                          "Soinu",                      "Son",                             "Ton",                                   "Sound",                             "Suono"},
  {"SUCCESS",                     "EXITO",                      "EXITO",                      "EXIT",                        "ARRAKASTA",                  "SUCCES",                          "ERFOLG",                                "SUCCESS",                           "SUCCESSO"},
  {"UPDATE_SALA",                 "Actualizar sala",            "Actualizar sala",            "Actualitzar sala",            "Gela eguneratu",             "Mettre a jour la salle",          "Raum aktualisieren",                    "Update room",                       "Aggiornare la stanza"},
  {"UPDATING",                    "Actualizando",               "Actualizando",               "Actualitzant",                "Eguneratzen",                "Mise a jour",                     "Aktualisiere",                          "Updating",                          "Aggiornamento"},
  {"VOLVER",                      "Volver",                     "Regresar",                   "Tornar",                      "Itzuli",                     "Retour",                          "Zuruck",                                "Back",                              "Indietro"},
  {"VOL_ATENUADO",                "Volumen atenuado",           "Volumen atenuado",           "Volum atenuat",               "Bolumen ahuldua",            "Volume attenue",                  "Gedampfte Lautstarke",                  "Soft volume",                       "Volume attenuato"},
  {"VOL_NORMAL",                  "Volumen normal",             "Volumen normal",             "Volum normal",                "Bolumen normala",            "Volume normal",                   "Normale Lautstarke",                    "Normal volume",                     "Volume normale"},
  {"VOL_MAXIMO",                  "Volumen maximo",             "Volumen maximo",             "Volum maxim",                 "Bolumen maximoa",            "Volume maximal",                  "Maximale Lautstarke",                   "Maximum volume",                    "Volume massimo"},
  {"YES_DELETE",                  "Si",                         "Si",                         "Si",                          "Bai",                        "Oui",                             "Ja",                                    "Yes",                               "Si"},
  {nullptr,                       nullptr,                      nullptr,                      nullptr,                       nullptr,                      nullptr,                             nullptr,                                nullptr,                            nullptr} // Entrada final
};



const char* getTranslation(const char* key) {
  for (int i = 0; translations[i].key != nullptr; i++) {
    if (strcmp(translations[i].key, key) == 0) {
      switch (currentLanguage) {
        case Language::ES:     return translations[i].es;
        case Language::ES_MX:  return translations[i].es_mx;
        case Language::CA:     return translations[i].ca;
        case Language::EU:     return translations[i].eu;
        case Language::FR:     return translations[i].fr;
        case Language::DE:     return translations[i].de;
        case Language::EN:     return translations[i].en;
        case Language::IT:     return translations[i].it;
        default:               return translations[i].es;
      }
    }
  }
  // Si no se encuentra la clave, se retorna la misma clave
  return key;
}
